apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack.yml
    kompose.version: 1.16.0 (HEAD)
  labels:
    io.kompose.service: adapter-xmi-ea
  name: adapter-xmi-ea
spec:
  minReadySeconds: 30
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: adapter-xmi-ea
  template:
    metadata:
      labels:
        io.kompose.service: adapter-xmi-ea
    spec:
      restartPolicy: Always
      volumes:
        - name: fint-oauth
          secret:
            secretName: fake-adapter.json
      containers:
        - name: adapter-xmi-ea
          image: fintlabs.azurecr.io/fint-xmi-ea-adapter:build.9
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            httpGet:
              port: 8091
              path: /health
          resources:
            limits:
              memory: "600Mi"
              cpu: "600m"
          volumeMounts:
            - name: fint-oauth
              mountPath: /var/fint/oauth
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+ExitOnOutOfMemoryError -Xmx300m -verbose:gc"
            - name: fint.adapter.sse-endpoint
              value: https://beta.felleskomponent.no/fint/metamodell/provider/sse/%s
            - name: fint.adapter.status-endpoint
              value: https://beta.felleskomponent.no/fint/metamodell/provider/status
            - name: fint.adapter.response-endpoint
              value: https://beta.felleskomponent.no/fint/metamodell/provider/response
            - name: fint.adapter.organizations
              value: fintlabs.no
            - name: fint.eaxmi.uri
              value: https://raw.githubusercontent.com/FINTprosjektet/fint-informasjonsmodell/master/FINT-informasjonsmodell.xml
            - name: fint.oauth.enabled
              value: "true"
            - name: fint.oauth.json
              value: file:/var/fint/oauth/fake-adapter.json
