apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack.yml
    kompose.version: 1.16.0 (HEAD)
  labels:
    io.kompose.service: adapter-xmi-ea
  name: adapter-xmi-ea
spec:
  minReadySeconds: 30
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: adapter-xmi-ea
  template:
    metadata:
      labels:
        io.kompose.service: adapter-xmi-ea
    spec:
      restartPolicy: Always
      containers:
        - name: adapter-xmi-ea
          image: fintlabs.azurecr.io/fint-xmi-ea-adapter:PR-2.5
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            httpGet:
              port: 8091
              path: /health
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+ExitOnOutOfMemoryError -Xmx256m -verbose:gc"
            - name: fint.adapter.sse-endpoint
              value: https://beta.felleskomponent.no/fint/metamodell/provider/sse/%s
            - name: fint.adapter.status-endpoint
              value: https://beta.felleskomponent.no/fint/metamodell/provider/status
            - name: fint.adapter.response-endpoint
              value: https://beta.felleskomponent.no/fint/metamodell/provider/response
            - name: fint.adapter.organizations
              value: fintlabs.no
            - name: fint.eaxmi.uri
              value: https://raw.githubusercontent.com/FINTprosjektet/fint-informasjonsmodell/master/FINT-informasjonsmodell.xml
            - name: fint.oauth.access-token-uri
              value: https://idp.felleskomponent.no/nidp/oauth/nam/token
            - name: fint.oauth.client-id
              valueFrom:
                secretKeyRef:
                  name: fake-adapter
                  key: client-id
            - name: fint.oauth.client-secret
              valueFrom:
                secretKeyRef:
                  name: fake-adapter
                  key: client-secret
            - name: fint.oauth.enabled
              value: "true"
            - name: fint.oauth.password
              valueFrom:
                secretKeyRef:
                  name: fake-adapter
                  key: password
            - name: fint.oauth.scope
              value: fint-client
            - name: fint.oauth.username
              valueFrom:
                secretKeyRef:
                  name: fake-adapter
                  key: username
